#!/usr/bin/env python3
from cnn_object_localization.astrobee_tf_broadcaster import *


if __name__ == "__main__":
    rospy.init_node("astrobee_tf_broadcaster_node")
    rospy.Subscriber("/gnc/ekf", EkfState, astrobee_pose_callback, buff_size=2**24)
    rospy.spin()