#!/usr/bin/env python3
from cnn_object_localization.icp_pose_estimator import *

if __name__ == "__main__":
    # Initialize node
    rospy.init_node("icp_pose_estimator_node")

    # Define detector object
    dm = DOFPoseEstimator()

    # Spin
    rospy.spin()
