services:
  astrobee-base:
    image: ${REMOTE:-astrobee}/astrobee:latest-base-ubuntu${UBUNTU_VERSION}
    build:
      context: ${ASTROBEE_PATH}
      dockerfile: ${ASTROBEE_PATH}/scripts/docker/astrobee_base.Dockerfile
      args:
        UBUNTU_VERSION: ${UBUNTU_VERSION:-20.04}
        ROS_VERSION: ${ROS_VERSION:-noetic}
        PYTHON: ${PYTHON:-3}

  astrobee:
    image: ${REMOTE:-astrobee}/astrobee:latest-ubuntu${UBUNTU_VERSION}
    build:
      context: ${ASTROBEE_PATH}
      dockerfile: ${ASTROBEE_PATH}/scripts/docker/astrobee.Dockerfile
      args:
        UBUNTU_VERSION: ${UBUNTU_VERSION:-20.04}
        REMOTE: ${REMOTE:-astrobee}
        ROS_VERSION: ${ROS_VERSION:-noetic}
        PYTHON: ${PYTHON:-3}
    links:
      - astrobee-base

  isaac-astrobee:
    links:
      - astrobee
