set instance jem_bay0 location
set instance jem_bay1 location
set instance jem_bay2 location
set instance jem_bay3 location
set instance jem_bay4 location
set instance jem_bay5 location
set instance jem_bay6 location
set instance jem_bay7 location
set instance jem_bay8 location
set instance berth1 location
set instance berth2 location
set instance bumble robot
set instance honey robot
set instance o0 order
set instance o1 order
set instance o2 order
set instance o3 order
set instance o4 order
set goal (and (completed-panorama bumble o0 jem_bay4) (completed-panorama bumble o1 jem_bay3) (completed-panorama bumble o2 jem_bay2) (completed-panorama bumble o3 jem_bay1) (completed-stereo bumble o4 jem_bay1 jem_bay4) (completed-panorama honey o0 jem_bay7) (completed-panorama honey o1 jem_bay6) (completed-panorama honey o2 jem_bay5) (robot-at honey berth2))
set predicate (move-connected jem_bay0 jem_bay1)
set predicate (move-connected jem_bay1 jem_bay0)
set predicate (move-connected jem_bay1 jem_bay2)
set predicate (move-connected jem_bay2 jem_bay1)
set predicate (move-connected jem_bay2 jem_bay3)
set predicate (move-connected jem_bay3 jem_bay2)
set predicate (move-connected jem_bay3 jem_bay4)
set predicate (move-connected jem_bay4 jem_bay3)
set predicate (move-connected jem_bay4 jem_bay5)
set predicate (move-connected jem_bay5 jem_bay4)
set predicate (move-connected jem_bay5 jem_bay6)
set predicate (move-connected jem_bay6 jem_bay5)
set predicate (move-connected jem_bay6 jem_bay7)
set predicate (move-connected jem_bay7 jem_bay6)
set predicate (move-connected jem_bay7 jem_bay8)
set predicate (move-connected jem_bay8 jem_bay7)
set predicate (location-real jem_bay1)
set predicate (location-real jem_bay2)
set predicate (location-real jem_bay3)
set predicate (location-real jem_bay4)
set predicate (location-real jem_bay5)
set predicate (location-real jem_bay6)
set predicate (location-real jem_bay7)
set predicate (dock-connected jem_bay7 berth1)
set predicate (dock-connected jem_bay7 berth2)
set predicate (robots-different bumble honey)
set predicate (robots-different honey bumble)
set predicate (locations-different jem_bay0 jem_bay1)
set predicate (locations-different jem_bay0 jem_bay2)
set predicate (locations-different jem_bay0 jem_bay3)
set predicate (locations-different jem_bay0 jem_bay4)
set predicate (locations-different jem_bay0 jem_bay5)
set predicate (locations-different jem_bay0 jem_bay6)
set predicate (locations-different jem_bay0 jem_bay7)
set predicate (locations-different jem_bay0 jem_bay8)
set predicate (locations-different jem_bay1 jem_bay0)
set predicate (locations-different jem_bay1 jem_bay2)
set predicate (locations-different jem_bay1 jem_bay3)
set predicate (locations-different jem_bay1 jem_bay4)
set predicate (locations-different jem_bay1 jem_bay5)
set predicate (locations-different jem_bay1 jem_bay6)
set predicate (locations-different jem_bay1 jem_bay7)
set predicate (locations-different jem_bay1 jem_bay8)
set predicate (locations-different jem_bay2 jem_bay0)
set predicate (locations-different jem_bay2 jem_bay1)
set predicate (locations-different jem_bay2 jem_bay3)
set predicate (locations-different jem_bay2 jem_bay4)
set predicate (locations-different jem_bay2 jem_bay5)
set predicate (locations-different jem_bay2 jem_bay6)
set predicate (locations-different jem_bay2 jem_bay7)
set predicate (locations-different jem_bay2 jem_bay8)
set predicate (locations-different jem_bay3 jem_bay0)
set predicate (locations-different jem_bay3 jem_bay1)
set predicate (locations-different jem_bay3 jem_bay2)
set predicate (locations-different jem_bay3 jem_bay4)
set predicate (locations-different jem_bay3 jem_bay5)
set predicate (locations-different jem_bay3 jem_bay6)
set predicate (locations-different jem_bay3 jem_bay7)
set predicate (locations-different jem_bay3 jem_bay8)
set predicate (locations-different jem_bay4 jem_bay0)
set predicate (locations-different jem_bay4 jem_bay1)
set predicate (locations-different jem_bay4 jem_bay2)
set predicate (locations-different jem_bay4 jem_bay3)
set predicate (locations-different jem_bay4 jem_bay5)
set predicate (locations-different jem_bay4 jem_bay6)
set predicate (locations-different jem_bay4 jem_bay7)
set predicate (locations-different jem_bay4 jem_bay8)
set predicate (locations-different jem_bay5 jem_bay0)
set predicate (locations-different jem_bay5 jem_bay1)
set predicate (locations-different jem_bay5 jem_bay2)
set predicate (locations-different jem_bay5 jem_bay3)
set predicate (locations-different jem_bay5 jem_bay4)
set predicate (locations-different jem_bay5 jem_bay6)
set predicate (locations-different jem_bay5 jem_bay7)
set predicate (locations-different jem_bay5 jem_bay8)
set predicate (locations-different jem_bay6 jem_bay0)
set predicate (locations-different jem_bay6 jem_bay1)
set predicate (locations-different jem_bay6 jem_bay2)
set predicate (locations-different jem_bay6 jem_bay3)
set predicate (locations-different jem_bay6 jem_bay4)
set predicate (locations-different jem_bay6 jem_bay5)
set predicate (locations-different jem_bay6 jem_bay7)
set predicate (locations-different jem_bay6 jem_bay8)
set predicate (locations-different jem_bay7 jem_bay0)
set predicate (locations-different jem_bay7 jem_bay1)
set predicate (locations-different jem_bay7 jem_bay2)
set predicate (locations-different jem_bay7 jem_bay3)
set predicate (locations-different jem_bay7 jem_bay4)
set predicate (locations-different jem_bay7 jem_bay5)
set predicate (locations-different jem_bay7 jem_bay6)
set predicate (locations-different jem_bay7 jem_bay8)
set predicate (locations-different jem_bay8 jem_bay0)
set predicate (locations-different jem_bay8 jem_bay1)
set predicate (locations-different jem_bay8 jem_bay2)
set predicate (locations-different jem_bay8 jem_bay3)
set predicate (locations-different jem_bay8 jem_bay4)
set predicate (locations-different jem_bay8 jem_bay5)
set predicate (locations-different jem_bay8 jem_bay6)
set predicate (locations-different jem_bay8 jem_bay7)
set predicate (robot-available bumble)
set predicate (robot-available honey)
set predicate (robot-at bumble berth1)
set predicate (robot-at honey berth2)
set predicate (location-available jem_bay0)
set predicate (location-available jem_bay1)
set predicate (location-available jem_bay2)
set predicate (location-available jem_bay3)
set predicate (location-available jem_bay4)
set predicate (location-available jem_bay5)
set predicate (location-available jem_bay6)
set predicate (location-available jem_bay7)
set predicate (location-available jem_bay8)
set predicate (need-stereo bumble o4 jem_bay1 jem_bay4)
set function (= (order-identity o0) 0)
set function (= (order-identity o1) 1)
set function (= (order-identity o2) 2)
set function (= (order-identity o3) 3)
set function (= (order-identity o4) 4)
set function (= (robot-order bumble) -1)
set function (= (robot-order honey) -1)
