#!/usr/bin/env python
# Copyright (c) 2017, United States Government, as represented by the
# Administrator of the National Aeronautics and Space Administration.
#
# All rights reserved.
#
# The Astrobee platform is licensed under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with the
# License. You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

"""
Snakemake rules for batch stitching multiple panoramas.
"""

from dot_dict import DotDict

# When using this Snakefile, use the --directory option to snakemake to set the
# desired output directory (e.g., "/output").

configfile: "pano_meta.yaml"

rule all:
    input:
        expand("{scene_id}/pano.png", scene_id=config["scenes"].keys())

# We set up an explicit check if the output pano exists before
# restitching.  This avoids unwanted restitching of all panos based on
# irrelevant changes to the Snakefile or configfile. Explicitly delete
# the output pano.png file if the pano needs to be restitched.

rule stitch:
    output:
        "{scene_id}/pano.png"
    params:
        s=lambda wildcards: DotDict(config["scenes"][wildcards.scene_id])
    shell:
        ("[ -f {output} ] ||"
         " /src/isaac/src/pano/pano_stitch/scripts/stitch_panorama.py"
         " --no-lens"
         " --robot={params.s.robot}"
         " --images-dir={params.s.images_dir}"
         " {params.s.bag_path}"
         " --output-dir={wildcards.scene_id}"
         " {params.s.extra_stitch_args}")
