(define (problem jem-survey)
    (:domain survey-manager)
    (:metric minimize (total-time))
    (:objects
        bay1 bay2 bay3 bay4 bay5 bay6 bay7 berth1 berth1-approach berth2 berth2-approach - location
        bumble honey - robot
        o-init o-any o0 o1 o2 o3 o4 o5 o6 o7 o8 o9 o10 o11 o12 o13 o14 o15 o16 o17 o18 o19 - order
        run1 run2 run3 run4 run5 - run-number
    )

    (:goal
        (and
            ;; Bumble
            (completed-panorama bumble o0 bay4 run1)
            (completed-panorama bumble o1 bay3 run1)
            (completed-panorama bumble o2 bay2 run1)
            (completed-panorama bumble o3 bay1 run1)
            (completed-stereo   bumble o4 bay1 bay4 run1)
            (robot-at bumble berth1)  ;; return to berth when done

            ;; Honey
            (completed-panorama honey o0 bay7 run1)
            (completed-panorama honey o1 bay6 run1)
            (completed-panorama honey o2 bay5 run1)
            (completed-stereo   honey o3 bay4 bay7 run1)
            (robot-at honey berth2)  ;; return to berth when done
        )
    )

    (:init
        ;; === Static predicates ===
        (move-connected bay1 bay2)
        (move-connected bay2 bay1)
        (move-connected bay2 bay3)
        (move-connected bay3 bay2)
        (move-connected bay3 bay4)
        (move-connected bay4 bay3)
        (move-connected bay4 bay5)
        (move-connected bay5 bay4)
        (move-connected bay5 bay6)
        (move-connected bay6 bay5)
        (move-connected bay6 bay7)
        (move-connected bay7 bay6)

        (move-connected bay6 berth1-approach)
        (move-connected berth1-approach bay6)
        (move-connected bay6 berth2-approach)
        (move-connected berth2-approach bay6)

        (move-connected bay7 berth1-approach)
        (move-connected berth1-approach bay7)
        (move-connected bay7 berth2-approach)
        (move-connected berth2-approach bay7)

        (dock-connected berth1-approach berth1)
        (dock-connected berth2-approach berth2)

        ;; Sorry, (21 choose 2) = 210 pairs to assert
        (order-before o-init o0)
        (order-before o-init o1)
        (order-before o-init o2)
        (order-before o-init o3)
        (order-before o-init o4)
        (order-before o-init o5)
        (order-before o-init o6)
        (order-before o-init o7)
        (order-before o-init o8)
        (order-before o-init o9)
        (order-before o-init o10)
        (order-before o-init o11)
        (order-before o-init o12)
        (order-before o-init o13)
        (order-before o-init o14)
        (order-before o-init o15)
        (order-before o-init o16)
        (order-before o-init o17)
        (order-before o-init o18)
        (order-before o-init o19)
        (order-before o0 o1)
        (order-before o0 o2)
        (order-before o0 o3)
        (order-before o0 o4)
        (order-before o0 o5)
        (order-before o0 o6)
        (order-before o0 o7)
        (order-before o0 o8)
        (order-before o0 o9)
        (order-before o0 o10)
        (order-before o0 o11)
        (order-before o0 o12)
        (order-before o0 o13)
        (order-before o0 o14)
        (order-before o0 o15)
        (order-before o0 o16)
        (order-before o0 o17)
        (order-before o0 o18)
        (order-before o0 o19)
        (order-before o1 o2)
        (order-before o1 o3)
        (order-before o1 o4)
        (order-before o1 o5)
        (order-before o1 o6)
        (order-before o1 o7)
        (order-before o1 o8)
        (order-before o1 o9)
        (order-before o1 o10)
        (order-before o1 o11)
        (order-before o1 o12)
        (order-before o1 o13)
        (order-before o1 o14)
        (order-before o1 o15)
        (order-before o1 o16)
        (order-before o1 o17)
        (order-before o1 o18)
        (order-before o1 o19)
        (order-before o2 o3)
        (order-before o2 o4)
        (order-before o2 o5)
        (order-before o2 o6)
        (order-before o2 o7)
        (order-before o2 o8)
        (order-before o2 o9)
        (order-before o2 o10)
        (order-before o2 o11)
        (order-before o2 o12)
        (order-before o2 o13)
        (order-before o2 o14)
        (order-before o2 o15)
        (order-before o2 o16)
        (order-before o2 o17)
        (order-before o2 o18)
        (order-before o2 o19)
        (order-before o3 o4)
        (order-before o3 o5)
        (order-before o3 o6)
        (order-before o3 o7)
        (order-before o3 o8)
        (order-before o3 o9)
        (order-before o3 o10)
        (order-before o3 o11)
        (order-before o3 o12)
        (order-before o3 o13)
        (order-before o3 o14)
        (order-before o3 o15)
        (order-before o3 o16)
        (order-before o3 o17)
        (order-before o3 o18)
        (order-before o3 o19)
        (order-before o4 o5)
        (order-before o4 o6)
        (order-before o4 o7)
        (order-before o4 o8)
        (order-before o4 o9)
        (order-before o4 o10)
        (order-before o4 o11)
        (order-before o4 o12)
        (order-before o4 o13)
        (order-before o4 o14)
        (order-before o4 o15)
        (order-before o4 o16)
        (order-before o4 o17)
        (order-before o4 o18)
        (order-before o4 o19)
        (order-before o5 o6)
        (order-before o5 o7)
        (order-before o5 o8)
        (order-before o5 o9)
        (order-before o5 o10)
        (order-before o5 o11)
        (order-before o5 o12)
        (order-before o5 o13)
        (order-before o5 o14)
        (order-before o5 o15)
        (order-before o5 o16)
        (order-before o5 o17)
        (order-before o5 o18)
        (order-before o5 o19)
        (order-before o6 o7)
        (order-before o6 o8)
        (order-before o6 o9)
        (order-before o6 o10)
        (order-before o6 o11)
        (order-before o6 o12)
        (order-before o6 o13)
        (order-before o6 o14)
        (order-before o6 o15)
        (order-before o6 o16)
        (order-before o6 o17)
        (order-before o6 o18)
        (order-before o6 o19)
        (order-before o7 o8)
        (order-before o7 o9)
        (order-before o7 o10)
        (order-before o7 o11)
        (order-before o7 o12)
        (order-before o7 o13)
        (order-before o7 o14)
        (order-before o7 o15)
        (order-before o7 o16)
        (order-before o7 o17)
        (order-before o7 o18)
        (order-before o7 o19)
        (order-before o8 o9)
        (order-before o8 o10)
        (order-before o8 o11)
        (order-before o8 o12)
        (order-before o8 o13)
        (order-before o8 o14)
        (order-before o8 o15)
        (order-before o8 o16)
        (order-before o8 o17)
        (order-before o8 o18)
        (order-before o8 o19)
        (order-before o9 o10)
        (order-before o9 o11)
        (order-before o9 o12)
        (order-before o9 o13)
        (order-before o9 o14)
        (order-before o9 o15)
        (order-before o9 o16)
        (order-before o9 o17)
        (order-before o9 o18)
        (order-before o9 o19)
        (order-before o10 o11)
        (order-before o10 o12)
        (order-before o10 o13)
        (order-before o10 o14)
        (order-before o10 o15)
        (order-before o10 o16)
        (order-before o10 o17)
        (order-before o10 o18)
        (order-before o10 o19)
        (order-before o11 o12)
        (order-before o11 o13)
        (order-before o11 o14)
        (order-before o11 o15)
        (order-before o11 o16)
        (order-before o11 o17)
        (order-before o11 o18)
        (order-before o11 o19)
        (order-before o12 o13)
        (order-before o12 o14)
        (order-before o12 o15)
        (order-before o12 o16)
        (order-before o12 o17)
        (order-before o12 o18)
        (order-before o12 o19)
        (order-before o13 o14)
        (order-before o13 o15)
        (order-before o13 o16)
        (order-before o13 o17)
        (order-before o13 o18)
        (order-before o13 o19)
        (order-before o14 o15)
        (order-before o14 o16)
        (order-before o14 o17)
        (order-before o14 o18)
        (order-before o14 o19)
        (order-before o15 o16)
        (order-before o15 o17)
        (order-before o15 o18)
        (order-before o15 o19)
        (order-before o16 o17)
        (order-before o16 o18)
        (order-before o16 o19)
        (order-before o17 o18)
        (order-before o17 o19)
        (order-before o18 o19)

        ;; === Dynamic predicates ===
        (robot-available bumble)
        (robot-available honey)

        (robot-at bumble berth1)
        (robot-at honey berth2)

        (robot-reserves bumble berth1)
        (robot-reserves honey berth2)

        (robot-order bumble o-init)
        (robot-order honey o-init)
    )  ;; end :init
)  ;; end problem
