name: vitstr
_target_: strhub.models.vitstr.system.ViTSTR

# Data
img_size: [ 224, 224 ]  # [ height, width ]
patch_size: [ 16, 16 ]  # [ height, width ]

# Architecture
embed_dim: 384
num_heads: 6

# Training
lr: 8.9e-4
